language: node_js

node_js:
  - "node"
  - "lts/*"

before_install:
  - npm install
  - cd examples
  - npm ci
  - cd ..

script:
  - npm test -- --coverage
  - cd examples
  - npm test -- --coverage
  - cd ..
