language: node_js

node_js:
  - "node"
  - "lts/*"

before_install:
  - npm install
  - npm install -g codecov

script:
  - npm test -- --coverage
  - npm run type:check
  - npm run prettier:check
  - npm run build
  - npm pack
  # Run the tests in the examples folder:
  - cd examples
  - npm install
  - npm install ../jest-websocket-mock-*
  - SKIP_PREFLIGHT_CHECK=true npm test -- --coverage
  - cd ..

after_success:
  - codecov
