language: node_js

node_js:
  - "node"
  - "lts/*"

before_install:
  - npm install
  - npm install -g codecov

script:
  - npm test -- --coverage
  - npm run type:check
  - npm run prettier:check
  - npm run build
  - npm pack
  # Run the tests in the examples folder
  # redux-saga:
  - cd examples/redux-saga
  - npm install
  - npm install ../../jest-websocket-mock-*
  - npm test -- --coverage
  # hooks:
  - cd ../hooks
  - npm install
  - npm install ../../jest-websocket-mock-*
  - npm test -- --coverage

after_success:
  - codecov
